# RAG QA System Configuration

retriever:
  type: faiss  # or chroma
  embedding_model: openai  # or sentence-transformers, etc.
  chunk_size: 500
  overlap: 50
  metadata_filtering: false
  rerank: false

generator:
  model: gpt-4  # or mistral, llama, etc.
  temperature: 0.2
  max_tokens: 512

pipeline:
  debug: true
  log_level: INFO
  interface: streamlit  # or cli
  ingest:
    sources:
      - pdfs
      - web
      - txt 